### ISSUE TITLE
Update package to 0.24.1

### ISSUE THREAD

**Issue by pascalberger** [kendaleiv/chocolatey-sql-operations-studio#3]
[December Public Preview 0.24.1](https://github.com/Microsoft/sqlopsstudio/releases/tag/v0.24.1) has been released and comes now with a Windows installer. It would be nice to have the package updated to the latest version and using the installer (or a `.install` and `.portable` package).

**Comment by kendaleiv** [comment]
Thanks for the feedback! I'm working on switching this package to use the installer.

**Comment by kendaleiv** [comment]
https://github.com/Microsoft/sqlopsstudio/issues/401

**Comment by pascalberger** [comment]
In the meantime there are already newer versions out (0.25.x). It would be nice to have this package auto-updating using an [AU](https://github.com/majkinetor/au) script (maybe you're interested in moving this over to https://github.com/chocolatey/chocolatey-coreteampackages/ where the AU infrastructure is already available?)

**Comment by kendaleiv** [comment]
0.26.7 is published. Closing.
